# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c95617ddc177127bad237677478b76fea41d36cd9045924a9bc58f9050a99a669dcab207dbe24c254f58f9f62259f58aa69a503b9e028bebc898545a90abd0d1

test:
  secret_key_base: f7a892f222ea5ed4f0a00b58179ca82d57246850f90c6f09a819ba6c80d81da7f13ccfd866a0d1dee3498df9baedb2935b6e18020dd6d52ff934a94ae8e7332b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
